receptor: <path_to_receptor.pdbqt>    # CORE rigid part of the receptor (PDBQT or PDB)
flex: <path_to_flex.pdbqt>            # flexible side chains, if any (PDBQT or PDB)
scoring: vina                         # CORE scoring function (ad4, vina, or vinardo)

ligand:
  single: <path_to_ligand.pdbqt>      # path to single ligand (PDBQT)
  index: <path_to_index.txt>          # CORE path to file containing paths to multiple ligands
  batch: <path_to_batch_ligands.pdbqt> # space-separated paths for batch mode
  gpu_batch: <path_to_gpu_batch_ligands.pdbqt> # space-separated paths for gpu batch mode
  min_HAC: <min_count>                # minimum number of heavy atoms
  max_HAC: <max_count>                # maximum number of heavy atoms
  min_logP: <min_val>                 # minimum logP value
  max_logP: <max_val>                 # maximum logP value

search_space:
  maps: <path_to_maps>                # affinity maps for the scoring function
  center_x: 0.0                       # CORE X coordinate of the center
  center_y: 0.0                       # CORE Y coordinate of the center
  center_z: 0.0                       # CORE Z coordinate of the center
  size_x: 20.0                        # CORE size in the X dimension
  size_y: 20.0                        # CORE size in the Y dimension
  size_z: 20.0                        # CORE size in the Z dimension
  autobox: true                       # set maps dimensions based on ligand

output:
  out: <output_models.pdbqt>          # output models
  dir: <output_directory>             # CORE output directory for batch mode
  write_maps: <output_filename>       # output filename for maps

misc:
  cpu: 4                              # number of CPUs to use
  seed: 123456                        # explicit random seed
  exhaustiveness: 8                   # exhaustiveness of the global search
  max_evals: 5000                     # number of evaluations in each MC run
  num_modes: 9                        # maximum number of binding modes
  min_rmsd: 1.0                       # minimum RMSD between output poses
  energy_range: 3                     # energy range for displayed poses
  spacing: 0.375                      # grid spacing
  verbosity: 1                        # verbosity level
  max_step: 1000                      # max number of steps in each MC run
  refine_step: 5                      # number of steps in refinement
  max_gpu_memory: 2048                # maximum GPU memory to use
  search_mode: balance                # CORE search mode (fast, balance, detail)

configuration_file:
  config: <path_to_config_file>       # path to external configuration file

information:
  help: false                         # if set to true, display usage summary
  help_advanced: false                # if set to true, display advanced options
  version: false                      # if set to true, display program version