receptor:
  path: "./data/mmp13_receptor.pdbqt"                         
  type: "pdbqt"

ligands:
  path: "./data/smiles_ligands.parquet"
  type: smiles

search_space:
  center_x: -6.9315
  center_y: 26.579
  center_z: 54.135999999999996
  size_x: 15.341000000000001
  size_y: 10.828
  size_z: 17.556000000000004

output:
  path: "./data/outputs"

optional:
  search_mode: fast                # CORE search mode (fast, balance, detail)